# Generated by Django 2.2.1 on 2019-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('c', 'Conference'), ('s', 'Seminar'), ('p', 'Presentation')], default='c', max_length=1)),
                ('slug', models.SlugField(default=0, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('register', models.BooleanField(default=False)),
                ('image', models.ImageField(default='img/no_image.png', upload_to='event')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('start_date',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
