# Generated by Django 2.2.2 on 2019-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.EmailField(max_length=254)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('register', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
