# Generated by Django 2.2.2 on 2019-06-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_slug'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='event',
            index_together={('id', 'slug')},
        ),
    ]
