# Generated by Django 2.2.2 on 2019-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190619_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Presentation', 'Presentation')], default='Conference', max_length=1),
        ),
    ]
