# Generated by Django 2.2.2 on 2019-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20190619_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='img/no_image.png', upload_to='event'),
        ),
    ]
