# Generated by Django 2.2.2 on 2019-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190619_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(default='img/no_image.png', upload_to='event'),
        ),
    ]
