# Generated by Django 2.2.2 on 2019-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.CharField(choices=[('a', 'a'), ('u', 'u')], default='u', max_length=1),
        ),
    ]
