# Generated by Django 2.2.2 on 2019-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190618_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'Admin'), ('u', 'User')], default='u', max_length=1),
        ),
    ]
